markdown: kramdown
title: Ebon - A complete responsive jekyll official website
author: anand_pal
author_email: anand.pal2050@gmail.com
description: Outsourcing is awesome, save your time
baseurl: /Ebon/
permalink: pretty
plugins:
  - jekyll-sitemap
